configure: fix fuse errors
Mellanox/rshim-user-space pull request #194
Opened 2024-10-15 16:11 UTC by vjardin

Fix the following syntax errors:
  ...
 checking for fuse... yes
 ./configure: line 5243: test: =: unary operator expected
 checking for pthread_create in -lpthread... yes
 checking that generated files are newer than configure... done
 configure: creating ./config.status
  ...

I will not check it for Freebsd or other OS, but there is obviously something wrong with the syntax.

2024-11-02 15:10 UTC, vjardin commented
Please, any comments ?

2024-11-06 17:06 UTC, vjardin commented
@vladsokolovsky : any comments ? It is a minor fix, but I guess it does not hurt.

2024-11-12 23:45 UTC, vjardin commented
please @pgeng-nv, any review ?

2024-11-13 00:03 UTC, vladsokolovsky commented on configure.ac
> +  if test "x$use_fuse3" = yes; then
Seems like this will never be true.

2024-11-13 01:40 UTC, vjardin commented on configure.ac
> +  if test "x$use_fuse3" = yes; then
right fixed, thanks for this comment !

2024-11-13 01:58 UTC, vladsokolovsky approved these changes

2024-11-13 02:56 UTC, lsun100 requested changes
Currently this repo is only maintained internally. To make it simpler, do you mind opening an Issue (https://github.com/Mellanox/rshim-user-space/issues) with the proposed fix included?

2024-11-13 07:59 UTC, vjardin commented
> Currently this repo is only maintained internally. To make it simpler, do you mind opening an Issue (https://github.com/Mellanox/rshim-user-space/issues) with the proposed fix included?

No way, you have the pull request so what's wrong ?

2024-11-15 18:15 UTC, lsun100 commented
> Please, any comments ?

We're in the process of updating the LICENSE file. Can we hold this pull request for now? Once the LICENSE file is updated, it'll be much easier to accept external contributions.

2024-11-25 03:14 UTC, lsun100 approved these changes

2024-11-25 03:15 UTC, merged